version: "3.9"
services:
  caddy:
    image: caddy:2.7.6-alpine
    container_name: caddy
    env_file: .env
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./wordpress/html:/var/www/html

  wordpress:
    image: joseluisq/php-fpm:8.3
    container_name: wordpress
    restart: always
    volumes:
      - ./wordpress/html:/var/www/html
      - ./wordpress/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    env_file: .env
