version: "3.9"
services:
  caddy:
    image: caddy:2.7.6-alpine
    container_name: caddy
    restart: always    
    env_file: ./config/.env
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./wordpress/html:/var/www/html

  php:
    image: joseluisq/php-fpm:8.3
    environment:
      - "ENV_SUBSTITUTION_ENABLE=true"    
    container_name: php
    restart: always
    volumes:
      - ./wordpress/html:/var/www/html
      - ./config/default-php.ini:/usr/local/etc/php/conf.d/default-php.ini
      - ./config/www.conf:/usr/local/etc/php-fpm.d/www.conf    
    env_file: ./config/.env
